name = "ci-runner-new-local"
executor = "local"
concurrent = 10
log_level = "debug"
listen_address = ":9252"
url = "http://10.134.13.25:9093/fconfigci-new"
artifact_path = "fdevtest-generic-local/fdev-ci-artifacts-sit"
[minio]
plugins_bucket = "fdev-ci-plugins-sit"
