image: mirrors.harbor.com/library/fdev-helper:latest

services:
  - 10.141.59.35/library/docker:dind-spdb

stages:
  - maven-build
  - deploy

variables:
  CI_REGISTRY: "10.141.59.35"
  CI_REGISTRY_IMAGE: "10.141.59.35/library/fdev-configserver"
  CI_REGISTRY_USER: "dockerimg"
  CI_REGISTRY_PASSWORD: "Spdb@1234"


maven-build:
  image: 10.141.59.35/library/maven:3-jdk-8
  stage: maven-build
  script:
    - mvn clean package -U -Dmaven.test.skip=true
    # - mvn sonar:sonar  -Dsonar.host.url=http://10.134.13.25:9000 -Dsonar.login=e6195643c4266cb57619e1cf4a62385ff61e49b9 -Dsonar.scm.provider=git
  artifacts:
          paths:
            - target/*.jar
  only:
    - /^UAT.*$/
    - /^SIT.*$/
    - master


ks8-deploy:
  stage: deploy
  script:
    - build_fdev.py
    - deploy_fdev.py
  only:
    - master
    - /^UAT.*$/
    - /^SIT.*$/
#    variables:
#      - $CI_DEPLOY == "deploy"
